name: ci

on:
  push:
    branches: main

jobs:
  build:
    runs-on: [self-hosted, macos]
    steps:
      - name: First job
        run: echo "Running on my self-hosted macOS runner"
      
      - name: Install Terraform
        uses: little-core-labs/install-terraform@v2.0.0
        with:
          version: 1.6.6   # 👈 put the Terraform version you want

      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
        
          client-id: 912307b0-0182-498b-bc35-68923aba3eb0
          # TenantId of the Azure Service principal created.
          tenant-id: df7d1ae3-5176-4f7e-914b-b0fbb8b85c9f
          # Azure subscriptionId
          subscription-id: 74282b2c-f351-49d2-8fc1-345ec077bafb
          # Set this value to true to enable Azure PowerShell Login in addition to Azure CLI login
          
      
  #     - name: Terraform init azurerm backend
  # # You may pin to the exact commit or the version.
  # # uses: ahmedig/terraform-azurerm-backend@65ed9d7f67790281b78670b7811d63d96f5e22ec
  #       uses: ahmedig/terraform-azurerm-backend@v4
  #       with:
  #   # Azure Credentials in JSON format
  #             azure_credentials: aaaa
  #             # State file location - resource group name
  #             resource_group_name: 
  #             # State file location - container name
  #             container_name: 
  #             # State file location - storage account name
  #             storage_account_name: 
  #             # State file location - file name
  #             # Subscription Id of the resource group
  #             subscription_id: # optional, default is empty
              # Terraform working directory
              # tf_working_directory: # optional, default is .
           
